#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/eduke32

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" eduke32$1

cd eduke32$1
git remote remove origin
git remote add origin https://voidpoint.io/terminx/eduke32.git
git fetch --all
git pull --ff-only origin master
git branch -u origin/master
