#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/prboom-plus

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" prboom-plus$1

cd prboom-plus$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/prboom-plus.git
git remote add coelckers https://github.com/coelckers/prboom-plus.git
git fetch --all
git pull coelckers master
git branch -u origin/master
