#!/bin/sh

set -o errexit

cd /Volumes/ramdisk
git clone https://github.com/coelckers/ZMusic.git zmusic-build

cd zmusic-build

if [ -n "$1" ]; then
	git checkout "$1"
fi

mkdir build

cd build

ZMUSIC_OS_MIN_VER=10.9
MACOS_SDK_DIR=/Volumes/Storage/Work/devbuilds/macos_sdk/MacOSX${ZMUSIC_OS_MIN_VER}.sdk
PREFIX_DIR=/Volumes/Storage/Work/zdoom-macos-deps/prefix

/Applications/CMake.app/Contents/bin/cmake                  \
	-DCMAKE_BUILD_TYPE=Release                              \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=${ZMUSIC_OS_MIN_VER}      \
	-DCMAKE_OSX_SYSROOT="${MACOS_SDK_DIR}"                  \
	-DCMAKE_PREFIX_PATH="${PREFIX_DIR}"                     \
	-DBUILD_SHARED_LIBS=OFF                                 \
	-DDYN_FLUIDSYNTH=OFF                                    \
	-DDYN_MPG123=OFF                                        \
	-DDYN_SNDFILE=OFF                                       \
	..
make -j2

libtool -static -o libzmusic.a                \
	source/libzmusic.a                        \
	thirdparty/adlmidi/libadl.a               \
	thirdparty/dumb/libdumb.a                 \
	thirdparty/game-music-emu/gme/libgme.a    \
	thirdparty/oplsynth/liboplsynth.a         \
	thirdparty/opnmidi/libopn.a               \
	thirdparty/timidity/libtimidity.a         \
	thirdparty/timidityplus/libtimidityplus.a \
	thirdparty/wildmidi/libwildmidi.a

libtool -static -o libzmusiclite.a            \
	source/libzmusiclite.a                    \
	thirdparty/dumb/libdumb.a                 \
	thirdparty/game-music-emu/gme/libgme.a
