#!/bin/sh

set -o errexit

cd /Volumes/ramdisk
git clone https://github.com/coelckers/ZMusic.git zmusic

cd zmusic

if [ -n "$1" ]; then
	git checkout "$1"
fi

mkdir build

cd build

ZMUSIC_OS_MIN_VER=10.9
MACOS_SDK_DIR=/Volumes/Storage/Work/devbuilds/macos_sdk/MacOSX${ZMUSIC_OS_MIN_VER}.sdk
DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
MPG123_DIR=${DEPS_DIR}mpg123/
SNDFILE_DIR=${DEPS_DIR}sndfile/
FSYNTH_DIR=${DEPS_DIR}fluidsynth/

/Applications/CMake.app/Contents/bin/cmake                  \
	-DCMAKE_BUILD_TYPE=Release                              \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=${ZMUSIC_OS_MIN_VER}      \
	-DCMAKE_OSX_SYSROOT="${MACOS_SDK_DIR}"                  \
	-DBUILD_SHARED_LIBS=OFF                                 \
	-DDYN_FLUIDSYNTH=OFF                                    \
	-DFLUIDSYNTH_INCLUDE_DIR="${FSYNTH_DIR}include"         \
	-DFLUIDSYNTH_LIBRARIES="${FSYNTH_DIR}/lib/fluidsynth.a" \
	-DDYN_MPG123=OFF                                        \
	-DMPG123_INCLUDE_DIR="${MPG123_DIR}include"             \
	-DMPG123_LIBRARIES="${MPG123_DIR}lib/libmpg123.a"       \
	-DDYN_SNDFILE=OFF                                       \
	-DSNDFILE_INCLUDE_DIR="${SNDFILE_DIR}include"           \
	-DSNDFILE_LIBRARY="${SNDFILE_DIR}lib/libsndfile.a"      \
	..
make -j2

libtool -static -o libzmusic.a                \
	source/libzmusic.a                        \
	thirdparty/adlmidi/libadl.a               \
	thirdparty/dumb/libdumb.a                 \
	thirdparty/game-music-emu/gme/libgme.a    \
	thirdparty/oplsynth/liboplsynth.a         \
	thirdparty/opnmidi/libopn.a               \
	thirdparty/timidity/libtimidity.a         \
	thirdparty/timidityplus/libtimidityplus.a \
	thirdparty/wildmidi/libwildmidi.a
