#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/zmusic

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" zmusic$1

cd zmusic$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/ZMusic.git
git remote add official https://github.com/ZDoom-Official/ZMusic.git
git fetch --all
git pull official master
git branch -u origin/master
