#!/bin/sh

set -o errexit

cd /Volumes/ramdisk/zmusic/build
libtool -static -o libzmusic.a                      \
	source/Debug/libzmusic.a                        \
	thirdparty/adlmidi/Debug/libadl.a               \
	thirdparty/dumb/Debug/libdumb.a                 \
	thirdparty/game-music-emu/gme/Debug/libgme.a    \
	thirdparty/oplsynth/Debug/liboplsynth.a         \
	thirdparty/opnmidi/Debug/libopn.a               \
	thirdparty/timidity/Debug/libtimidity.a         \
	thirdparty/timidityplus/Debug/libtimidityplus.a \
	thirdparty/wildmidi/Debug/libwildmidi.a
