#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/openal-soft

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" openal-soft$1

cd openal-soft$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/openal-soft.git
git remote add kcat https://github.com/kcat/openal-soft.git
git fetch --all
git pull kcat master
git branch -u origin/master
