#!/bin/sh

DIR="`dirname \"$0\"`/"
URL="http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz"

${DIR}install_ogg
${DIR}install_vorbis
${DIR}install_flac

${DIR}do_install ${URL} --enable-static --disable-shared
