#!/bin/sh

if [ ! -z ${BUILD_OGG_INSTALLED+x} ]; then
	exit
fi

INST="`dirname \"$0\"`/do_install"
URL="https://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz"

${INST} ${URL} --enable-static --disable-shared

export BUILD_OGG_INSTALLED=1
