#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/wadext

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" wadext$1

cd wadext$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/wadext.git
git remote add coelckers https://github.com/coelckers/wadext.git
git fetch --all
git pull coelckers master
git branch -u origin/master

