#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/
DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
SOURCE_DIR=/Volumes/ramdisk/slade$1

if [ ! -e "${SOURCE_DIR}" ]; then
	"${SCRIPT_DIR}git_clone" $1
fi

"${DEPS_DIR}build.py" --xcode --source="${SOURCE_DIR}" --build-path="${SOURCE_DIR}/cmake-build-debug" \
	--os-version-x64=10.10 --sdk-path-x64=/Volumes/Storage/Work/devbuilds/macos_sdk/MacOSX10.11.sdk
