#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/slade

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" slade$1

cd slade$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/SLADE.git
git remote add sirjuddington https://github.com/sirjuddington/SLADE.git
git fetch --all
git checkout -b master origin/master
git branch -D osx
git pull sirjuddington master
