#!/bin/sh

set -o errexit

export PATH=$PATH:/Applications/CMake.app/Contents/bin

cd /Volumes/ramdisk
git clone https://github.com/KhronosGroup/MoltenVK.git

cd MoltenVK

if [ ! -z "$1" ]; then
	git checkout "$1"
fi

./fetchDependencies --macos --no-parallel-build -v
xcodebuild -project MoltenVK/MoltenVK.xcodeproj -scheme MoltenVK-macOS
