#!/bin/sh

set -o errexit

BUILD_ROOT=/Volumes/ramdisk/dosbox_build
AUTOTOOLS_PREFIX=${BUILD_ROOT}/autotools
SDL2_PREFIX=${BUILD_ROOT}/SDL2
PATH=${AUTOTOOLS_PREFIX}/bin:${SDL2_PREFIX}/bin:$PATH

if [ ! -e "${BUILD_ROOT}" ]; then
	mkdir -p "${BUILD_ROOT}"
fi

cd "${BUILD_ROOT}"
curl -OL http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
tar -xzf autoconf-2.69.tar.gz

cd autoconf-2.69
./configure --prefix="${AUTOTOOLS_PREFIX}"
make install

cd ..
curl -OL http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz
tar -xzf automake-1.15.tar.gz

cd automake-1.15
./configure --prefix="${AUTOTOOLS_PREFIX}"
make install

cd ..
curl -OL http://libsdl.org/release/SDL2-2.0.5.tar.gz
tar -xzf SDL2-2.0.5.tar.gz

cd SDL2-2.0.5
./configure --prefix="${SDL2_PREFIX}" --disable-shared --enable-static
make install

cd ..
curl -OL https://github.com/nigels-com/glew/releases/download/glew-2.0.0/glew-2.0.0.tgz
tar -xzf glew-2.0.0.tgz

cd glew-2.0.0
make lib lib/libGLEW.a

cd ..
git clone https://github.com/alexey-lysiuk/dosbox.git

GLEW_PREFIX=${BUILD_ROOT}/glew-2.0.0
GLEW_INCLUDE=${GLEW_PREFIX}/include
declare -x CFLAGS=-I"${GLEW_INCLUDE}"
declare -x CPPFLAGS=-I"${GLEW_INCLUDE}"
declare -x CXXFLAGS=-I"${GLEW_INCLUDE}"
declare -x LDFLAGS=-L"${GLEW_PREFIX}/lib"

cd dosbox
./autogen.sh
./configure --enable-core-inline --disable-debug
make
