#!/bin/sh

# See artifacts at https://github.com/fte-team/fteqw/actions/ for commit and build date
COMMIT=ef58bce8b08089852bd8f89752f2ef4c9a5c8010
SRC_DIR=fteqw-$COMMIT
SRC_TARGZ=$SRC_DIR.tar.gz
SRC_SHA256=5e89b8dfb0937c41694b95b8ad1541e53f624828deb6156e961321100d7181f5
BUILD_DIR=$SRC_DIR/build
CMAKE_EXE=$(which cmake)

if [ -z $CMAKE_EXE ]; then
	CMAKE_EXE=/Applications/CMake.app/Contents/bin/cmake
fi

set -o errexit

curl -JOL https://github.com/fte-team/fteqw/archive/$COMMIT.tar.gz
printf "$SRC_SHA256  $SRC_TARGZ\n" | shasum -a 256 -c
tar -xf $SRC_TARGZ

"$CMAKE_EXE" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_C_FLAGS="-DSVNREVISION=git-30-ef58bce -DSVNDATE=2025-06-10" \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
	-S $SRC_DIR \
	-B $BUILD_DIR
"$CMAKE_EXE" \
	--build $BUILD_DIR \
	--target fteqcc
