#!/bin/sh

# See artifacts at https://github.com/fte-team/fteqw/actions/ for commit and build date
COMMIT=5662b3a23d3c16f5a3b5fe74efb88e77d8fc4da0
SRC_DIR=fteqw-$COMMIT
SRC_TARGZ=$SRC_DIR.tar.gz
SRC_SHA256=5f30366f51ecdf56be8e233e2fb3ba42bec9185ae9a5c04d2aff947b45933342
BUILD_DIR=$SRC_DIR/build
CMAKE_EXE=$(which cmake)

if [ -z $CMAKE_EXE ]; then
	CMAKE_EXE=/Applications/CMake.app/Contents/bin/cmake
fi

set -o errexit

curl -JOL https://github.com/fte-team/fteqw/archive/$COMMIT.tar.gz
printf "$SRC_SHA256  $SRC_TARGZ\n" | shasum -a 256 -c
tar -xf $SRC_TARGZ

"$CMAKE_EXE" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_C_FLAGS="-DSVNREVISION=git-6681-5662b3a23 -DSVNDATE=2025-02-01" \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
	-S $SRC_DIR \
	-B $BUILD_DIR
"$CMAKE_EXE" \
	--build $BUILD_DIR \
	--target fteqcc
