#!/bin/sh

# See artifacts at https://github.com/fte-team/fteqw/actions/ for commit and build date
COMMIT=09768089c006f242c10be2a044968d15ecb99d29
SRC_DIR=fteqw-$COMMIT
SRC_TARGZ=$SRC_DIR.tar.gz
SRC_SHA256=17f37e39db8bd9f6dae7973dc05435e8d60a5951078416632faf271755e67faf
BUILD_DIR=$SRC_DIR/build
CMAKE_EXE=$(which cmake)

if [ -z $CMAKE_EXE ]; then
	CMAKE_EXE=/Applications/CMake.app/Contents/bin/cmake
fi

set -o errexit

curl -JOL https://github.com/fte-team/fteqw/archive/$COMMIT.tar.gz
printf "$SRC_SHA256  $SRC_TARGZ\n" | shasum -a 256 -c
tar -xf $SRC_TARGZ

"$CMAKE_EXE" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_C_FLAGS="-DSVNREVISION=git-30-0976808 -DSVNDATE=2024-09-14" \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
	-S $SRC_DIR \
	-B $BUILD_DIR
"$CMAKE_EXE" \
	--build $BUILD_DIR \
	--target fteqcc
