#!/bin/sh

CMAKE_EXE=`which cmake`

if [ -z $CMAKE_EXE ]; then
	CMAKE_EXE=/Applications/CMake.app/Contents/bin/cmake
fi

set -o errexit

cd /Volumes/ramdisk
mkdir libcxx
cd libcxx

# Download source code

curl -O http://llvm.org/releases/3.8.0/llvm-3.8.0.src.tar.xz
curl -O http://llvm.org/releases/3.8.0/libcxx-3.8.0.src.tar.xz
curl -O http://llvm.org/releases/3.8.0/libcxxabi-3.8.0.src.tar.xz

tar xf llvm-3.8.0.src.tar.xz 
tar xf libcxx-3.8.0.src.tar.xz 
tar xf libcxxabi-3.8.0.src.tar.xz

# Configure and build libc++

mkdir libcxx_build
cd libcxx_build
${CMAKE_EXE} \
	-DLLVM_PATH=../llvm-3.8.0.src \
	-DLIBCXX_CXX_ABI=libcxxabi \
	-DLIBCXX_CXX_ABI_INCLUDE_PATHS=../libcxxabi-3.8.0.src/include \
	-DLIBCXX_ENABLE_SHARED=NO \
	-DCMAKE_OSX_ARCHITECTURES="i386;x86_64" \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=10.4 \
	../libcxx-3.8.0.src
make
cd ..

# Configure and build libc++abi

mkdir libcxxabi_build
cd libcxxabi_build
${CMAKE_EXE} \
	-DLLVM_PATH=../llvm-3.8.0.src \
	-DLIBCXXABI_LIBCXX_PATH=../libcxx-3.8.0.src \
	-DLIBCXXABI_ENABLE_SHARED=NO \
	-DLLVM_NO_OLD_LIBSTDCXX=YES \
	-DCMAKE_OSX_ARCHITECTURES="i386;x86_64" \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=10.4 \
	../libcxxabi-3.8.0.src
make
cd ..

# Create ready-to-use include and lib directories

cp -R libcxx-3.8.0.src/include .
cp -R libcxxabi-3.8.0.src/include .
rm include/CMakeLists.txt
rm include/__config_site.in

mkdir lib
cp libcxx_build/lib/libc++.a lib
cp libcxxabi_build/lib/libc++abi.a lib

# Fix undefined symbols __eprintf for architecture i386

cd lib
gcc -c -xc -o eprintf.o -arch i386 -O2 -mmacosx-version-min=10.4 - <<EOF

#include <stdio.h>
#include <stdlib.h>

void __eprintf(const char *fmt, const char *expr, int line, const char *file)
{
	fprintf(stderr, fmt, expr, line, file);
	fflush(stderr);

	abort();
}

EOF

lipo libc++abi.a -thin x86_64 -output libc++abi_x64.a
lipo libc++abi.a -thin i386 -output libc++abi_i386.a
ar -r libc++abi_i386.a eprintf.o
rm libc++abi.a
lipo libc++abi_i386.a libc++abi_x64.a -create -output libc++abi.a
rm libc++abi_i386.a
rm libc++abi_x64.a
rm eprintf.o
