#!/bin/sh

set -o errexit

BUILD_ROOT=/Volumes/ramdisk/libsndfile-debug

if [ ! -e "${BUILD_ROOT}" ]; then
	mkdir -p "${BUILD_ROOT}"
fi

cd ${BUILD_ROOT}
curl -O https://pkg-config.freedesktop.org/releases/pkg-config-0.29.1.tar.gz
curl -O http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz
curl -O http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz
curl -O http://downloads.xiph.org/releases/flac/flac-1.3.2.tar.xz
curl -O http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.27.tar.gz

tar -xf pkg-config-0.29.1.tar.gz
tar -xf libogg-1.3.2.tar.xz
tar -xf libvorbis-1.3.5.tar.xz
tar -xf flac-1.3.2.tar.xz
tar -xf libsndfile-1.0.27.tar.gz

export PREFIX=${BUILD_ROOT}/dist
export CFLAGS=-O0\ -g\ -I${PREFIX}/include
export PATH=${PREFIX}/bin:${PATH}

cd pkg-config-0.29.1
./configure --prefix="${PREFIX}" --with-internal-glib
make install
cd ..

cd libogg-1.3.2
./configure --prefix="${PREFIX}" --disable-shared
make install
cd ..

cd libvorbis-1.3.5
./configure --prefix="${PREFIX}" --disable-shared
make install
cd ..

cd flac-1.3.2
./configure --prefix="${PREFIX}" --disable-shared --enable-static
make install
cd ..

cd libsndfile-1.0.27
./configure --prefix="${PREFIX}" --disable-shared
make install
