#!/bin/sh

set -o errexit

cd /Volumes/ramdisk
mkdir qres_extract

cd qres_extract
curl -JOL 'https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtbase-everywhere-src-5.15.2.tar.xz'
curl -JOL 'https://github.com/tatokis/qresExtract/raw/0ba8c103f0ee7dd083b3b7f9d3a00a2c21a3392a/main.cpp'

echo "909fad2591ee367993a75d7e2ea50ad4db332f05e1c38dd7a5a274e156a4e0f8  qtbase-everywhere-src-5.15.2.tar.xz" >> checksum.sha256
echo "219333674950e2d2be60c8ce2d1033613279f126986b5b015b0d39db92c6947a  main.cpp" >> checksum.sha256
shasum -c checksum.sha256

tar -xf qtbase-everywhere-src-5.15.2.tar.xz

cd qtbase-everywhere-src-5.15.2
./configure -static -release -opensource -confirm-license

cd src
../bin/qmake -o Makefile src.pro
make -j $(sysctl -n hw.ncpu) sub-corelib

cd ../..
clang++ -std=c++11 -Wno-deprecated-declarations -Iqtbase-everywhere-src-5.15.2/include -Iqtbase-everywhere-src-5.15.2/include/QtCore -Lqtbase-everywhere-src-5.15.2/lib -lQt5Core -lqtpcre2 -framework Cocoa -framework IOKit -framework Security -lz -o qresExtract main.cpp
