#!/bin/sh

VERSION=3.9.0
LLVM_VERSION=llvm-${VERSION}

LLVM_SRC=${LLVM_VERSION}.src
LLVM_TARBALL=${LLVM_SRC}.tar.xz

LLVM_PREFIX=/usr/local

CMAKE_EXE=`which cmake`

if [ -z $CMAKE_EXE ]; then
	CMAKE_EXE=/Applications/CMake.app/Contents/bin/cmake
fi

set -o errexit

cd /Volumes/ramdisk

mkdir llvm-build
cd llvm-build

curl -O http://llvm.org/releases/${VERSION}/${LLVM_TARBALL}
tar -xf ${LLVM_TARBALL}
rm ${LLVM_TARBALL}

cd ${LLVM_SRC}
mkdir build

cd build
"${CMAKE_EXE}" \
	-DCMAKE_BUILD_TYPE="Release" \
	-DCMAKE_CXX_FLAGS="-stdlib=libc++" \
	-DCMAKE_INSTALL_PREFIX="${LLVM_PREFIX}" \
	-DCMAKE_OSX_DEPLOYMENT_TARGET="10.8" \
	-DLLVM_TARGETS_TO_BUILD="X86" \
	-DLLVM_ENABLE_RTTI="YES" \
	..
make

LLVM_INSTALL_IMAGE=../../${LLVM_VERSION}.sparseimage
LLVM_FINAL_IMAGE=../../${LLVM_VERSION}.dmg

hdiutil create -size 320m -type SPARSE -fs HFS+ -volname ${LLVM_VERSION} -ov ${LLVM_INSTALL_IMAGE}
sudo hdiutil attach -mountpoint ${LLVM_PREFIX} ${LLVM_INSTALL_IMAGE}

make install

hdiutil detach ${LLVM_PREFIX}
hdiutil convert ${LLVM_INSTALL_IMAGE} -format UDBZ -ov -o ${LLVM_FINAL_IMAGE}
