#!/bin/sh

set -o errexit

cd /Volumes/ramdisk
git clone https://github.com/alexey-lysiuk/bym.git

cd bym/src
ln -s configuration_user.py.sample configuration_user.py
ln -s repository_user.py.sample repository_user.py

cd ..
open /Applications/PyCharm\ CE.app --args `pwd`
