#!/bin/sh

set -o errexit

MIRRORS_ROOT_DIR=/Volumes/Storage/Work/mirrors/
TINYSA_MIRROR_DIR=$MIRRORS_ROOT_DIR/tinySA
CHIBIOS_MIRROR_DIR=$MIRRORS_ROOT_DIR/ChibiOS

ORIGIN_URL=https://github.com/alexey-lysiuk/tinySA.git
UPSTREAM_URL=https://github.com/erikkaashoek/tinySA.git
CHIBIOS_URL=https://github.com/edy555/ChibiOS.git

TINYSA_DIR=/Volumes/ramdisk/tinySA

if [ -e "$TINYSA_MIRROR_DIR" ]; then
	git -C "$TINYSA_MIRROR_DIR" fetch --all --tags
else
	git clone --mirror $ORIGIN_URL "$TINYSA_MIRROR_DIR"

	cd "$TINYSA_MIRROR_DIR"
	git remote add upstream $UPSTREAM_URL
	git fetch --all --tags
	git gc
fi

if [ -e "$CHIBIOS_MIRROR_DIR" ]; then
	git -C "$CHIBIOS_MIRROR_DIR" fetch --all --tags
else
	git clone --mirror "$CHIBIOS_URL" "$CHIBIOS_MIRROR_DIR"
fi

git clone --shared "$TINYSA_MIRROR_DIR" "$TINYSA_DIR"

cd "$TINYSA_DIR"
git remote remove origin
git remote add origin "$ORIGIN_URL"
git remote add upstream $UPSTREAM_URL
git fetch --all --tags
git branch --set-upstream-to=origin/main
git pull --ff-only upstream main
git submodule update --init --recursive --reference "$CHIBIOS_MIRROR_DIR"
