#!/bin/sh

set -o errexit

PROJECT=SDRPlusPlus
ORIGIN_URL=https://github.com/alexey-lysiuk/$PROJECT.git
UPSTREAM_URL=https://github.com/AlexandreRouma/$PROJECT.git

MIRROR_DIR=/Volumes/Storage/Work/mirrors/$PROJECT
WORK_DIR=/Volumes/ramdisk/$PROJECT

if [ ! -e "$MIRROR_DIR" ]; then
	git clone --mirror "$ORIGIN_URL" "$MIRROR_DIR"

	cd "$MIRROR_DIR"
	git remote add upstream "$UPSTREAM_URL"
	git fetch --all --tags
	git gc
fi

git -C "$MIRROR_DIR" fetch --all --tags
git clone --shared "$MIRROR_DIR" "$WORK_DIR"

cd "$WORK_DIR"
git remote remove origin
git remote add origin "$ORIGIN_URL"
git remote add upstream "$UPSTREAM_URL"
git fetch --all --tags
git branch --set-upstream-to=origin/master
git pull --ff-only upstream master
