#!/bin/sh

set -o errexit

ORIGIN_URL=https://github.com/alexey-lysiuk/sdrpp-exp.git
UPSTREAM_URL=https://github.com/AlexandreRouma/SDRPlusPlus.git

MIRROR_DIR=/Volumes/Storage/Work/mirrors/sdrpp-exp
WORK_DIR=/Volumes/ramdisk/sdrpp-exp

if [ -e "$MIRROR_DIR" ]; then
	git -C "$MIRROR_DIR" fetch --all --tags
else
	git clone --mirror $ORIGIN_URL "$MIRROR_DIR"

	cd "$MIRROR_DIR"
	git remote add upstream $UPSTREAM_URL
	git fetch --all --tags
	git gc
fi

git clone --shared "$MIRROR_DIR" "$WORK_DIR"

cd "$WORK_DIR"
git remote remove origin
git remote add origin $ORIGIN_URL
git remote add upstream $UPSTREAM_URL
git fetch --all --tags
git branch --set-upstream-to=origin/main
git pull --ff-only origin main
git switch upstream
git pull --ff-only upstream master
git switch main
