#!/bin/sh

cd /Volumes/ramdisk

git clone https://github.com/alexey-lysiuk/doomretro.git
cd doomretro

git remote add bradharding https://github.com/bradharding/doomretro.git
git fetch --all
git pull bradharding master

open xcode/doomretroapp.xcodeproj
