#!/bin/sh

set -o errexit

BASE_DIR=/Volumes/Storage/Work/
BUILD_ENV_DIR=${BASE_DIR}gzdoom-macos-build
GZDOOM_DIR=${BASE_DIR}gzdoom_devbuild

cd "${BUILD_ENV_DIR}"
git pull

cd "${GZDOOM_DIR}"
git pull

cd /Volumes/ramdisk
git clone "${BUILD_ENV_DIR}"

cd gzdoom-macos-build
git clone "${GZDOOM_DIR}" gzdoom

./build_gzdoom
