#!/bin/sh

set -o errexit

cd /Volumes/ramdisk

if [ ! -e gz_build ]; then
	mkdir gz_build
fi

cd gz_build

TP_DIR=/Volumes/Storage/Work/GZDoom/thirdparty/
FMOD_DIR=${TP_DIR}FMOD/
OPENAL_DIR=${TP_DIR}openal-soft/
MPG123_DIR=${TP_DIR}mpg123/
FSYNTH_DIR=${TP_DIR}fluidsynth/
FSYNTH_LIB_PREFIX=${FSYNTH_DIR}lib/lib
FSYNTH_LIBS=${FSYNTH_LIB_PREFIX}fluidsynth.a\;${FSYNTH_LIB_PREFIX}glib-2.0.a\;${FSYNTH_LIB_PREFIX}intl.a
SNDFILE_DIR=${TP_DIR}sndfile/
SNDFILE_LIB_PREFIX=${SNDFILE_DIR}lib/lib
SNDFILE_LIBS=${SNDFILE_LIB_PREFIX}sndfile.a\;${SNDFILE_LIB_PREFIX}FLAC.a\;${SNDFILE_LIB_PREFIX}ogg.a\;${SNDFILE_LIB_PREFIX}vorbis.a\;${SNDFILE_LIB_PREFIX}vorbisenc.a
SDL2_DIR=${TP_DIR}SDL2/
FRAMEWORKS=-framework\ AudioUnit\ -framework\ AudioToolbox\ -framework\ CoreAudio\ -framework\ ForceFeedback

SRC_DIR=../gzdoom

if [ ! -e ${SRC_DIR} ]; then
	SRC_DIR=/Volumes/Storage/Work/gz_temp
fi

CMAKE_CXX_FLAGS=-Wno-inconsistent-missing-override\ -D__FP__\ -D__FIXMATH__

/Applications/CMake.app/Contents/bin/cmake -Wno-dev -GXcode  \
	-DOSX_COCOA_BACKEND=YES                                  \
	-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"                   \
	-DCMAKE_OSX_DEPLOYMENT_TARGET="10.7"                     \
	-DCMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY="libc++"       \
	-DCMAKE_EXE_LINKER_FLAGS="${FRAMEWORKS}"                 \
	-DFMOD_INCLUDE_DIR=${FMOD_DIR}inc                        \
	-DFMOD_LIBRARY=${FMOD_DIR}lib/libfmodex.dylib            \
	-DOPENAL_INCLUDE_DIR=${OPENAL_DIR}include                \
	-DOPENAL_LIBRARY=${OPENAL_DIR}lib/libopenal.a            \
	-DMPG123_INCLUDE_DIR=${MPG123_DIR}include                \
	-DMPG123_LIBRARIES=${MPG123_DIR}lib/libmpg123.a          \
	-DFLUIDSYNTH_INCLUDE_DIR=${FLUIDSYNTH_DIR}include        \
	-DFLUIDSYNTH_LIBRARIES=${FSYNTH_LIBS}                    \
	-DSNDFILE_INCLUDE_DIR=${SNDFILE_DIR}include              \
	-DSNDFILE_LIBRARY=${SNDFILE_LIBS}                        \
	-DSDL2_INCLUDE_DIR=${SDL2_DIR}include                    \
	-DSDL2_LIBRARY=${SDL2_DIR}lib/libSDL2.a                  \
	${SRC_DIR}

function open_xcode_project {
	if grep -qi project\\s*\(\\s*$1\\s*\) ${SRC_DIR}/CMakeLists.txt; then
		open $1.xcodeproj
	fi
}

open_xcode_project ZDoom
open_xcode_project GZDoom
