#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/NBlood

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" 

cd NBlood
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/NBlood.git
git remote add nukeykt https://github.com/nukeykt/NBlood.git
git fetch --all
git pull nukeykt master
git branch -u origin/master

open platform/Apple/EDuke32.xcodeproj
