#!/bin/sh

set -o errexit

function sync_remote {
	git remote remove origin
	git remote add origin https://github.com/alexey-lysiuk/$1.git
	git fetch --all
	git branch -u origin/master
	git pull
}

cd /Volumes/ramdisk
git clone -s /Volumes/Storage/Work/mirrors/r667aaa

cd r667aaa
sync_remote Realm667-AAA

git clone -s /Volumes/Storage/Work/mirrors/r667aaa-cache cache

cd cache
sync_remote Realm667-AAA-Cache
