#!/bin/sh

set -o errexit

BASE_DIR=/Volumes/Storage/Work/
BUILD_ENV=slade-macos-build
BUILD_ENV_DIR=${BASE_DIR}${BUILD_ENV}
SLADE_DIR=${BASE_DIR}devbuilds/slade

cd "${BUILD_ENV_DIR}"
git pull

cd "${SLADE_DIR}"
git pull

cd /Volumes/ramdisk
git clone -s "${BUILD_ENV_DIR}"

cd ${BUILD_ENV}
git clone -s "${SLADE_DIR}" SLADE

cd SLADE
SLADE_VERSION=SLADE-`git describe --tags`

plutil -replace LSMinimumSystemVersion -string "10.7" Info.plist
plutil -replace CFBundleVersion -string "${SLADE_VERSION}" Info.plist
plutil -replace CFBundleShortVersionString -string "${SLADE_VERSION}" Info.plist
plutil -replace CFBundleLongVersionString -string "${SLADE_VERSION}" Info.plist
plutil -replace NSSupportsAutomaticGraphicsSwitching -bool true Info.plist

../make_dmg.sh $@
