#!/bin/sh

set -o errexit

cd /Volumes/ramdisk
git clone -s /Volumes/Storage/Work/mirrors/slade-macos-build

cd slade-macos-build
git clone -s /Volumes/Storage/Work/mirrors/slade

cd slade
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/SLADE.git
git remote add sirjuddington https://github.com/sirjuddington/SLADE.git
git fetch --all
git checkout -b master sirjuddington/master

cd ..
./xcode.sh
