#!/bin/sh

set -o errexit

BASE_DIR=/Volumes/Storage/Work/
BUILD_ENV=slade-macos-build
BUILD_ENV_DIR=${BASE_DIR}${BUILD_ENV}
SLADE_DIR=${BASE_DIR}slade_devbuild

cd "${BUILD_ENV_DIR}"
git pull

cd "${SLADE_DIR}"
git pull

cd /Volumes/ramdisk
git clone "${BUILD_ENV_DIR}"

cd ${BUILD_ENV}
git clone "${SLADE_DIR}" SLADE

./make_dmg.sh $@
