#!/bin/sh

set -o errexit

cd /Volumes/Storage/Work/mirrors

function update_mirror {
	DIR=$1
	URL=$2

	echo "[*] Updating ${DIR}..."

	if [ ! -e ${DIR} ]; then
		git clone --mirror ${URL} ${DIR}

		if (( $# > 2 )); then
			cd ${DIR}

			for REMOTE_URL in ${@:3}; do
				REMOTE_NAME=${REMOTE_URL%/*}
				REMOTE_NAME=${REMOTE_NAME##*/}
				git remote add ${REMOTE_NAME} ${REMOTE_URL}
			done

			git fetch --all
			git gc

			cd ..
		fi
	fi

	cd ${DIR}
	git fetch --all
	cd ..
}

GH=https://github.com/

# my repositories
AL=${AL}
update_mirror gzdoom-macos \
	${AL}gzdoom.git \
	${GH}rheit/zdoom.git \
	${GH}coelckers/gzdoom.git \
	${GH}raa-eruanna/qzdoom.git
update_mirror zdoom-macos-deps ${AL}zdoom-macos-deps.git
update_mirror prboom-macos ${AL}prboom-macos.git
update_mirror r667aaa ${AL}Realm667-AAA.git
update_mirror r667aaa-cache ${AL}Realm667-AAA-Cache.git
update_mirror slade \
	${AL}SLADE.git \
	${GH}sirjuddington/SLADE.git
update_mirror slade-macos-build ${AL}slade-macos-build.git
update_mirror tools ${AL}tools.git
update_mirror macos-sdk ${AL}macos-sdk.git

# id software
IDSOFT=${GH}id-Software/
update_mirror wolf3d ${IDSOFT}wolf3d.git
update_mirror wolf3d-ios ${IDSOFT}Wolf3D-iOS.git
update_mirror wolf3d-browser ${IDSOFT}wolf3d-browser.git
update_mirror doom ${IDSOFT}DOOM.git
update_mirror idsetup ${IDSOFT}idsetup.git
update_mirror doom-ios ${IDSOFT}DOOM-iOS.git
update_mirror doom-ios-v2 ${IDSOFT}DOOM-IOS2.git
update_mirror quake ${IDSOFT}Quake.git
update_mirror quake-tools ${IDSOFT}Quake-Tools.git
update_mirror quake2 ${IDSOFT}Quake-2.git
update_mirror quake2-tools ${IDSOFT}Quake-2-Tools.git
update_mirror quake3 ${IDSOFT}Quake-III-Arena.git
update_mirror gtkradiant ${IDSOFT}GtkRadiant.git
update_mirror rtcw-sp ${IDSOFT}RTCW-SP.git
update_mirror rtcw-mp ${IDSOFT}RTCW-MP.git
update_mirror doom3 ${IDSOFT}DOOM-3.git
update_mirror doom3-bfg ${IDSOFT}DOOM-3-BFG.git
update_mirror enemy-territory ${IDSOFT}Enemy-Territory.git

# games
update_mirror iwad-patches ${GH}Doom-Utils/iwad-patches.git
update_mirror historic-ports ${GH}Doom-Utils/historic-ports.git
update_mirror doom3do ${GH}Olde-Skuul/doom3do.git
update_mirror chocolate-doom ${GH}chocolate-doom/chocolate-doom.git
update_mirror eternity ${GH}team-eternity/eternity.git
update_mirror zdoom-old ${GH}doomtech/zdoom-old.git
update_mirror gzdoom-svn ${GH}doomtech/gzdoom.git
update_mirror freedoom ${GH}freedoom/freedoom.git
update_mirror strife-ve ${GH}svkaiser/strife-ve.git
update_mirror powerslave-ex ${GH}svkaiser/PowerslaveEX.git
update_mirror doomrl ${GH}ChaosForge/doomrl.git
update_mirror fpcvalkyrie ${GH}ChaosForge/fpcvalkyrie.git
update_mirror serious-engine ${GH}Croteam-official/Serious-Engine.git
update_mirror shadowgrounds ${GH}vayerx/shadowgrounds.git
update_mirror darkplaces ${GH}xonotic/darkplaces.git
update_mirror freeablo ${GH}wheybags/freeablo.git
update_mirror dgengine ${GH}dgengin/DGEngine.git
update_mirror postal ${GH}iammeat/POSTAL-1-Open-Source.git
update_mirror xray-15 ${GH}OpenXRay/xray.git
update_mirror xray-16 ${GH}OpenXRay/xray-16.git

# tools
update_mirror mucommander ${GH}mucommander/mucommander.git
update_mirror trolcommander ${GH}trol73/mucommander.git
update_mirror hexfiend ${GH}ridiculousfish/HexFiend.git
update_mirror gfxcardstatus ${GH}codykrieger/gfxCardStatus.git
update_mirror hwsensors ${GH}kozlek/HWSensors.git
update_mirror acc ${GH}rheit/acc.git
update_mirror zdbsp ${GH}rheit/zdbsp.git
update_mirror wadext ${GH}coelckers/wadext.git
update_mirror gzdoombuilder ${GH}m-x-d/GZDoom-Builder.git
update_mirror dosbox ${GH}duganchen/dosbox.git
