#!/bin/sh

set -o errexit

cd /Volumes/ramdisk

if [ ! -e vx16 ]; then
	git clone https://github.com/alexey-lysiuk/vx16.git
fi

cd vx16

if [ ! -e build ]; then
	mkdir build
fi

cd build
/Applications/CMake.app/Contents/bin/cmake             \
	-GXcode                                            \
	-DCMAKE_CXX_FLAGS="-std=c++11"                     \
	-DCMAKE_OSX_DEPLOYMENT_TARGET="10.7"               \
	-DCMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY="libc++" \
	..

open vx16.xcodeproj
