#!/bin/sh

cd /Volumes/ramdisk

git clone https://github.com/alexey-lysiuk/yquake2-osx-build.git yquake2
cd yquake2

git clone https://github.com/alexey-lysiuk/yquake2.git
cd yquake2

git remote add yamagi https://github.com/yquake2/yquake2.git
git fetch --all
cd ..

git clone https://github.com/alexey-lysiuk/xatrix.git
cd xatrix

git remote add yamagi https://github.com/yquake2/xatrix
git fetch --all
cd ..

git clone https://github.com/alexey-lysiuk/rogue.git
cd rogue

git remote add yamagi https://github.com/yquake2/rogue.git
git fetch --all
cd ..

git clone https://github.com/alexey-lysiuk/zaero.git
cd zaero

git remote add yamagi https://github.com/yquake2/zaero.git
git fetch --all
