#!/bin/sh

set -o errexit

cd /Volumes/ramdisk
git clone -s /Volumes/Storage/Work/mirrors/zdoom-macos-deps

cd zdoom-macos-deps
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/zdoom-macos-deps.git
git fetch --all
git branch -u origin/master
git pull
