#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/

DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
PREFIX=${DEPS_DIR}prefix

SOURCE_DIR=/Volumes/ramdisk/a6r-tools
BUILD_DIR=${SOURCE_DIR}/build

if [ ! -e "${SOURCE_DIR}" ]; then
	"${SCRIPT_DIR}clone"
fi

# Make sure prefix directory is up-to-date
"${DEPS_DIR}build.py" --target=build-prefix

"${PREFIX}/bin/cmake" \
	-S "${SOURCE_DIR}" \
	-B "${BUILD_DIR}" \
	-DCMAKE_PREFIX_PATH="${PREFIX}" \
	-GXcode

open "${BUILD_DIR}/a6r-tools.xcodeproj"
