#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/
DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
WORK_DIR=/Volumes/ramdisk/
SOURCE_DIR=${WORK_DIR}quakespasm-cmake

if [ ! -e "${SOURCE_DIR}" ]; then
	"${SCRIPT_DIR}git_clone_cmake"
fi

# Make deps directory is up-to-date
git -C "${DEPS_DIR}" pull --ff-only
"${DEPS_DIR}build.py" --target=build-prefix

PREFIX=${DEPS_DIR}prefix
CMAKE_EXE=${PREFIX}/bin/cmake
LINKER_FLAGS=$("${PREFIX}/bin/pkg-config" --libs ogg sdl2)
BUILD_DIR=${SOURCE_DIR}/build/spiked_package

"${CMAKE_EXE}" \
	-DCMAKE_PREFIX_PATH="${PREFIX}" \
	-DCMAKE_EXE_LINKER_FLAGS="${LINKER_FLAGS}" \
	-DCMAKE_OSX_DEPLOYMENT_TARGET="10.15" \
	-DQUAKE_TARGET=quakespasm-spiked \
	-DQUAKE_MACOS_BUNDLE=OFF \
	-B"${BUILD_DIR}" \
	-S"${SOURCE_DIR}"
"${CMAKE_EXE}" --build "${BUILD_DIR}" --parallel

SPIKED_REVISION=$(git -C "${SOURCE_DIR}/src/quakespasm-spiked" rev-parse --short HEAD)
tar -C "${BUILD_DIR}" -cJf "${WORK_DIR}quakespasm-spiked-bin@${SPIKED_REVISION}.tar.xz" quakespasm-spiked quakespasm.pak
