#!/bin/sh

set -o errexit

WORK_DIR=/Volumes/ramdisk/

MIRRORS_DIR=/Volumes/Storage/Work/mirrors/
SOURCE_MIRROR_DIR=${MIRRORS_DIR}quakespasm-cmake
SUBMODULES_MIRROR_DIR=${MIRRORS_DIR}quakespasm

cd "${SOURCE_MIRROR_DIR}"
git fetch --all

cd "${SUBMODULES_MIRROR_DIR}"
git fetch --all --tags

cd "${WORK_DIR}"
git clone -s "${SOURCE_MIRROR_DIR}"

cd quakespasm-cmake
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/quakespasm-cmake.git
git fetch --all
git pull --ff-only origin main
git branch -u origin/main

for submodule in quakespasm quakespasm-spiked vkquake ironwail; do
	git submodule update --init --reference "${SUBMODULES_MIRROR_DIR}" "src/${submodule}"

	if [[ "${submodule}" == 'quakespasm-spiked' ]]; then
		branch=qsrebase
	else
		branch=master
	fi

	git -C "src/${submodule}" checkout ${branch}
done
