#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)
SOURCE_DIR=${SCRIPT_DIR}/../../../game_tools/bsputil
BUILD_DIR=/Volumes/ramdisk/bsputil_build

mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"

/Applications/CMake.app/Contents/bin/cmake -GXcode "${SOURCE_DIR}"
open bsputil.xcodeproj
