#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/
DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
SOURCE_DIR=/Volumes/ramdisk/quakespasm-exp$1
BUILD_DIR=${SOURCE_DIR}/build

if [ ! -e "${SOURCE_DIR}" ]; then
	"${SCRIPT_DIR}git_clone_exp" $1
fi

"${DEPS_DIR}build.py" --xcode --source="${SOURCE_DIR}" --build-path="${BUILD_DIR}"

cd "${BUILD_DIR}"
rsync -a /Volumes/Storage/Documents/Quake/Games/* Debug
