#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/
DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
SOURCE_DIR=/Volumes/ramdisk/quakespasm-exp$1
BUILD_DIR=${SOURCE_DIR}/build

git -C "${DEPS_DIR}" pull --ff-only

if [ ! -e "${SOURCE_DIR}" ]; then
	"${SCRIPT_DIR}git_clone_exp" $1
fi

"${DEPS_DIR}build.py" --xcode --source="${SOURCE_DIR}" --build-path="${BUILD_DIR}"

BUILD_DEBUG_DIR=${BUILD_DIR}/Debug
BUILD_ID1_DIR=${BUILD_DEBUG_DIR}/id1

rsync -a /Volumes/Storage/Documents/Quake/Games/* "${BUILD_DEBUG_DIR}"

if [ ! -e "${BUILD_ID1_DIR}/scripts" ]; then
	ln -s "${SOURCE_DIR}/Misc/qs_pak/scripts" "${BUILD_ID1_DIR}"
fi
