#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)
WORK_DIR=/Volumes/ramdisk
DEPS_DIR=$WORK_DIR/games-macos-deps
SOURCE_DIR=$WORK_DIR/quakespasm-exp$1
BUILD_DIR=$SOURCE_DIR/build

if [ ! -e "$DEPS_DIR" ]; then
	"$SCRIPT_DIR/../macos-deps/clone-games"
fi

git -C "$DEPS_DIR" pull --ff-only

if [ ! -e "$SOURCE_DIR" ]; then
	"$SCRIPT_DIR/clone_exp" $1
fi

"$DEPS_DIR/build.py" --xcode --source="$SOURCE_DIR" --build-path="$BUILD_DIR"

BUILD_DEBUG_DIR=$BUILD_DIR/Debug
BUILD_ID1_DIR=$BUILD_DEBUG_DIR/id1

rsync -a /Volumes/Storage/Documents/Quake/Games/* "$BUILD_DEBUG_DIR"
sed -i '' -e 's/vid_fullscreen 1/vid_width 1440;vid_height 900;nosound 1;bgmvolume 0;map e1m1/' "$BUILD_DEBUG_DIR/id1/autoexec.cfg"

SCRIPTS_DIR=$SOURCE_DIR/Misc/qs_pak/scripts

if [ ! -e "$BUILD_ID1_DIR/scripts" ]; then
	ln -s "$SCRIPTS_DIR" "$BUILD_ID1_DIR"
fi

open -b dev.zed.Zed "$SCRIPTS_DIR"
