#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/quakespasm

cd "${SRC_REPO_DIR}"
git fetch --all --tags

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" vkquake$1

cd vkquake$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/vkQuake.git
git remote add upstream https://github.com/Novum/vkQuake.git
git fetch --all --tags
git checkout -b master origin/master
git branch -D main
git pull upstream master
