#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/quakespasm

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" quakespasm-spiked$1

cd quakespasm-spiked$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/quakespasm-spiked.git
git remote add upstream https://github.com/Shpoike/Quakespasm.git
git fetch --all
git checkout -b qsrebase origin/qsrebase
git branch -D main
git pull upstream qsrebase
