#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/quakespasm

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" quakespasm-exp$1

cd quakespasm-exp$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/quakespasm-exp.git
git remote add upstream https://git.code.sf.net/p/quakespasm/quakespasm
git fetch --all
git pull --ff-only origin main
git branch -u origin/main
git tag -d $(git tag -l)
