#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/quakespasm

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" quakespasm$1

cd quakespasm$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/quakespasm.git
git remote add upstream https://git.code.sf.net/p/quakespasm/quakespasm
git remote add ironwail https://github.com/andrei-drexler/ironwail.git
git fetch --all
git checkout -b master origin/master
git branch -D main
git pull --ff-only upstream master
