#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/zdoom-macos-deps

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}"

cd zdoom-macos-deps
git remote remove origin
git remote add origin https://github.com/ZDoom/zdoom-macos-deps.git
git fetch --all
git branch -u origin/main
git pull --ff-only

mkdir sdk

for sdk in /Volumes/Storage/Work/devbuilds/macos_sdk/*; do
	ln -s "$sdk" sdk
done
