#!/bin/sh

set -o errexit

SOURCE_DIR=/Volumes/ramdisk/zdoom-macos-deps
SCRIPT_DIR=$(cd "${0%/*}"; pwd)/

if [ ! -e "${SOURCE_DIR}" ]; then
	"${SCRIPT_DIR}git_clone"
fi

open -b com.jetbrains.pycharm.ce "${SOURCE_DIR}"
"${SOURCE_DIR}/build.py" --target=build-prefix
