#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/Raze

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" raze$1

cd raze$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/Raze.git
git remote add coelckers https://github.com/coelckers/Raze.git
git fetch --all
git pull --ff-only coelckers master
git branch -u origin/master
