#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/raze

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" raze$1

cd raze$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/Raze.git
git remote add official https://github.com/ZDoom-Official/Raze.git
git fetch --all
git pull --ff-only official master
git branch -u origin/master
