#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/
P7ZIP_EXE=${SCRIPT_DIR}7za

if [ -z "$1" ]; then
	echo "Usage: dmgextract file.dmg"
	exit
fi

if [ ! -e "$P7ZIP_EXE" ]; then
	pushd "$SCRIPT_DIR"
	mkdir build

	SRC_FILE=p7zip_16.02_src_all.tar.bz2

	cd build
	curl -LO https://downloads.sourceforge.net/project/p7zip/p7zip/16.02/$SRC_FILE

	SRC_SUM1=$(shasum -a 256 $SRC_FILE)
	SRC_SUM2=5eb20ac0e2944f6cb9c2d51dd6c4518941c185347d4089ea89087ffdd6e2341f

	if [ "${SRC_SUM1:0:64}" != "$SRC_SUM2" ]; then
		echo "ERROR: Checksum mismatch for $SRC_FILE"
		exit 1
	fi

	tar -xf $SRC_FILE

	cd p7zip_16.02
	cp makefile.macosx_llvm_64bits makefile.machine
	make 7za
	mv p7zip_16.02/bin/7za ..
	
	popd
fi

"$P7ZIP_EXE" x "$1"