#!/bin/sh

set -o errexit

if [ "$#" -eq 0 ]; then
	echo "Usage: dmgmount file.dmg ..."
	exit
fi

for f in "$@"; do
	MOUNTPOINT=$(basename -s .dmg "$f")

	if [ ! -e "$MOUNTPOINT" ]; then
		mkdir "$MOUNTPOINT"
	fi

	hdiutil attach "$f" -mountpoint "$MOUNTPOINT" -noverify
done
