#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/
DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
SOURCE_DIR=/Volumes/ramdisk/gzdoom$1

if [ ! -e "${SOURCE_DIR}" ]; then
	"${SCRIPT_DIR}clone" $1
fi

"${DEPS_DIR}build.py" --xcode --source="${SOURCE_DIR}" --build-path="${SOURCE_DIR}/build"
