#!/bin/sh

set -o errexit

MIRRORS_ROOT_DIR=/Volumes/Storage/Work/mirrors/

if [ -z "$PROJECT" ]; then
	echo 'ERROR: PROJECT variable is not set'
	exit 1
fi

if [ -z "$REPO_URL" ]; then
	REPO_URL=https://github.com/aedi-org/$PROJECT.git
fi

MIRROR_DIR=$MIRRORS_ROOT_DIR$PROJECT
WORK_DIR=/Volumes/ramdisk/$PROJECT

CORE_REPO_URL=https://github.com/aedi-org/core.git
CORE_MIRROR_DIR=${MIRRORS_ROOT_DIR}aedi-core

if [ -e "$MIRROR_DIR" ]; then
	git -C "$MIRROR_DIR" fetch --all --tags
else
	git clone --mirror "$REPO_URL" "$MIRROR_DIR"
fi

if [ -e "$CORE_MIRROR_DIR" ]; then
	git -C "$CORE_MIRROR_DIR" fetch --all --tags
else
	git clone --mirror "$CORE_REPO_URL" "$CORE_MIRROR_DIR"
fi

if [ ! -e "$WORK_DIR" ]; then
	git clone --shared "$MIRROR_DIR" "$WORK_DIR"

	cd "$WORK_DIR"
	git remote remove origin
	git remote add origin "$REPO_URL"
	git fetch --all
	git branch -u origin/main
	git pull --ff-only
	git submodule update --init --recursive --reference "$CORE_MIRROR_DIR"
fi
