#!/bin/sh

cd /Volumes/ramdisk

if [ -e gzdoom ]; then
	echo Error: gzdoom directory is already exist!
	exit 1
fi

git clone https://github.com/alexey-lysiuk/gzdoom.git
cd gzdoom

#mkdir misc/freedoom
#cp ~/Library/Application\ Support/GZDoom/freedoom*.wad misc/freedoom

PACKAGE_NAME=GZDoom-`git describe`

xcodebuild -target make_deploy_cocoa -configuration MaxOptim
mv .deploy_image/${PACKAGE_NAME}.dmg ..
#mv .deploy_image/Free${PACKAGE_NAME}.dmg ..

SYMBOLS_ARCHIVE_NAME=${PACKAGE_NAME}.dSYM.zip

cd build/MaxOptim
zip -9r ${SYMBOLS_ARCHIVE_NAME} GZDoom_Cocoa.app.dSYM
mv ${SYMBOLS_ARCHIVE_NAME} ../../..
