#!/bin/sh

set -o errexit

SCRIPT_DIR=$(cd "${0%/*}"; pwd)/

cd /Volumes/ramdisk

if [ ! -e zdoom$1 ]; then
	"${SCRIPT_DIR}git_clone" $1
fi

cd zdoom$1

ZDOOM_PROJECT=$("${SCRIPT_DIR}project.py")
MACOS_MIN_VER=10.7

if [ ! -e build ]; then
	mkdir build
fi

cd build

DEPS_DIR=/Volumes/Storage/Work/zdoom-macos-deps/
FMOD_DIR=${DEPS_DIR}fmodex/
OPENAL_DIR=${DEPS_DIR}openal/
MPG123_DIR=${DEPS_DIR}mpg123/
SNDFILE_DIR=${DEPS_DIR}sndfile/
FSYNTH_DIR=${DEPS_DIR}fluidsynth/
FSYNTH_LIB_PREFIX=${FSYNTH_DIR}lib/lib
FSYNTH_LIBS=${FSYNTH_LIB_PREFIX}fluidsynth.a\;${FSYNTH_LIB_PREFIX}glib-2.0.a\;${FSYNTH_LIB_PREFIX}intl.a
SDL_DIR=${DEPS_DIR}sdl/
OTHER_LIBS=-liconv\ -L${DEPS_DIR}ogg/lib\ -logg\ -L${DEPS_DIR}vorbis/lib\ -lvorbis\ -lvorbisenc\ -L${DEPS_DIR}flac/lib\ -lFLAC
FRAMEWORKS=-framework\ AudioUnit\ -framework\ AudioToolbox\ -framework\ Carbon\ -framework\ CoreAudio\ -framework\ CoreMIDI\ -framework\ CoreVideo\ -framework\ ForceFeedback
LINKER_FLAGS=${OTHER_LIBS}\ ${FRAMEWORKS}

/Applications/CMake.app/Contents/bin/cmake -GXcode   \
	-DOSX_COCOA_BACKEND=YES                          \
	-DDYN_OPENAL=NO                                  \
	-DDYN_MPG123=NO                                  \
	-DDYN_SNDFILE=NO                                 \
	-DDYN_FLUIDSYNTH=NO                              \
	-DFORCE_INTERNAL_ZLIB=YES                        \
	-DFORCE_INTERNAL_JPEG=YES                        \
	-DFORCE_INTERNAL_BZIP2=YES                       \
	-DFORCE_INTERNAL_GME=YES                         \
	-DCMAKE_OSX_DEPLOYMENT_TARGET="${MACOS_MIN_VER}" \
	-DCMAKE_EXE_LINKER_FLAGS="${LINKER_FLAGS}"       \
	-DFMOD_INCLUDE_DIR=${FMOD_DIR}inc                \
	-DFMOD_LIBRARY=${FMOD_DIR}lib/libfmodex.dylib    \
	-DOPENAL_INCLUDE_DIR=${OPENAL_DIR}include        \
	-DOPENAL_LIBRARY=${OPENAL_DIR}lib/libopenal.a    \
	-DMPG123_INCLUDE_DIR=${MPG123_DIR}include        \
	-DMPG123_LIBRARIES=${MPG123_DIR}lib/libmpg123.a  \
	-DSNDFILE_INCLUDE_DIR=${SNDFILE_DIR}include      \
	-DSNDFILE_LIBRARY=${SNDFILE_DIR}lib/libsndfile.a \
	-DFLUIDSYNTH_INCLUDE_DIR=${FSYNTH_DIR}include    \
	-DFLUIDSYNTH_LIBRARIES=${FSYNTH_LIBS}            \
	-DSDL2_INCLUDE_DIR=${SDL_DIR}include             \
	-DSDL2_LIBRARY=${SDL_DIR}lib/libSDL2.a           \
	..

open ${ZDOOM_PROJECT}.xcodeproj
