#!/bin/sh

set -o errexit

MIRRORS_DIR=/Volumes/Storage/Work/mirrors/
SRC_REPO_DIR=${MIRRORS_DIR}gzdoom-macos

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" zdoom$1

cd zdoom$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/gzdoom.git
git remote add zdoom-org https://github.com/ZDoom/gzdoom.git
# Additional remotes, disabled by default
#git remote add rheit https://github.com/rheit/zdoom.git
#git remote add qzdoom https://github.com/ZDoom/qzdoom.git
#git remote add legacy https://github.com/drfrag666/gzdoom.git
git fetch --all
git checkout -b master origin/master
git branch -D macOS
git pull --ff-only zdoom-org master
