#!/bin/sh

set -o errexit

SRC_REPO_DIR=/Volumes/Storage/Work/mirrors/devilutionX

cd "${SRC_REPO_DIR}"
git fetch --all

cd /Volumes/ramdisk
git clone -s "${SRC_REPO_DIR}" devilutionX$1

cd devilutionX$1
git remote remove origin
git remote add origin https://github.com/alexey-lysiuk/devilutionX.git
git remote add diasurgical https://github.com/diasurgical/devilutionX.git
git fetch --all
git pull diasurgical master
git branch -u origin/master
